### ISSUE TITLE
Autoloader for Template

### ISSUE THREAD

**Issue by Ma3xl3** [hypergalaktisch/contao-parallax#1]
First thx for your plugin.

If enable the parallax function in an article and you dont have added the xl_parallax_mod_article.html5 in your local template folder you will get the following error:

**Could not find template "xl_parallax_mod_article" thrown in system/modules/core/library/Contao/TemplateLoader.php on line 123**

To solve this problem you have to add an autoload.php in your config folder and load the Template as defined:

TemplateLoader::addFiles(array
(
	'xl_parallax_mod_article'   => 'system/modules/xl-parallax/templates'
));

Can you add this to your next version?

**Comment by hypergalaktisch** [comment]
Fixed
