### ISSUE TITLE
Fehlermeldung nach Installation Contao [4.4.14]

### ISSUE THREAD

**Issue by operatorone** [hypergalaktisch/contao-parallax#4]
Nach der Installation erscheint beim Aufruf des Backends folgende Meldung:

> Attempted to load class "HookListener" from namespace "Hypergalaktisch\ParallaxBundle\EventListener". Did you forget a "use" statement for "Hypergalaktisch\ParallaxBundle\Eventlistener\HookListener"?

**Comment by rorych** [comment]
Same here, also with Contao 4.4.14

**Comment by operatorone** [comment]
Hi, for the time being there's a workaround if you have time pressure. 

Download the parallax.js package from http://pixelcog.github.io/parallax.js/. Put the JS file in the folder /files/js. Create a template named js_parallax.html5 and put it in the template folder. Content of the template is `<?php
$GLOBALS['TL_JAVASCRIPT'][] = 'files/js/parallax.js|static';
?>`
The parallax.min.js can also be used. Activate the template in the expert section of your page layout as javascript template, not jquery.

In the article create two HTML content elements sourrounding your content. 

The first has the content 
`<div class="parallax-window" data-parallax="scroll" data-image-src="/files/images/Name-of-the-image.jpg">` the second just `</div>`

It should look like this:

HTML-CE 1
-- Text-CE
-- Image-CE
HTML-CE 2

Put this line in your CSS/LESS: 
`.parallax-window {
    min-height: 400px;
    background: transparent;
}`

And thats it. You should be able to use the parallax in an article now.

**Comment by rorych** [comment]
Thanks for the effort!
Perfect, i'll try that.

**Comment by operatorone** [comment]
I made it work when I used "composer update -o" in the console.

**Comment by operatorone** [comment]
Error still appears after update when I open up the backend. Very annoying!

Attempted to load class "HookListener" from namespace "Hypergalaktisch\ParallaxBundle\EventListener". Did you forget a "use" statement for "Hypergalaktisch\ParallaxBundle\Eventlistener\HookListener"?

**Comment by operatorone** [comment]
Thanks for the fix.

**Comment by operatorone** [comment]
Sorry. Updated. Error message again.

Attempted to load class "HookListener" from namespace "Hypergalaktisch\ParallaxBundle\EventListener". Did you forget a "use" statement for e.g. "Hypergalaktisch\ParallaxBundle\Eventlistener\HookListener" or "Glumanda99\RellaxBundle\EventListener\HookListener"?

**Comment by hypergalaktisch** [comment]
Have you tried to clear the cache and update the composer class loader?

**Comment by operatorone** [comment]
Yup. Tried vendor/bin/contao-console cache:clear --no-warmup and vendor/bin/contao-console cache:warmup
