### ISSUE TITLE
PHP Fehler: Attempted to load class HookListener

### ISSUE THREAD

**Issue by cwittstock** [hypergalaktisch/contao-parallax#5]
Nach der Installation des Moduls bekommen wir folgenden Fehler:

 app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"HookListener\" from namespace \"Hypergalaktisch\\ParallaxBundle\\EventListener\".\nDid you forget a \"use\" statement for \"Hypergalaktisch\\ParallaxBundle\\Eventlistener\\HookListener\"? at /var/customers/webs/barby/perlys.nnhl.de/var/cache/prod/ContainerGdkodgs/getHypergalaktischParallax_Listener_HooksService.php:8)"} []

Contao Version ist 4.4.18.
Webserver läuft mit Apache und PHP7.

**Comment by operatorone** [comment]
Fehler besteht immer noch. Gibt es da schon eine korrigierte Version?

**Comment by hypergalaktisch** [comment]
Ich kann das Problem bei mir nicht nachstellen, wird der Fehler immer noch angezeigt?

**Comment by operatorone** [comment]
Hi, ich glaube nun passt alles. Habe gestern aktualisiert und der Fehler trat nicht mehr auf. Danke sehr :-)

**Comment by hypergalaktisch** [comment]
Perfekt :-)
