### ISSUE TITLE
Composer error with HookListener

### ISSUE THREAD

**Issue by koertho** [hypergalaktisch/contao-parallax#6]
Hi, when I install your bundle, everytime I open my site I get an error: `Attempted to load class "HookListener" from namespace "Hypergalaktisch\ParallaxBundle\EventListener".
Did you forget a "use" statement for e.g. "Hypergalaktisch\ParallaxBundle\Eventlistener\HookListener"`
The event listener is called in the parseTemplate Hook, so even the backend doesn't work anymore.

There seems to be an error with the composer autoload configuration. It works, if I use the optimized autoloader (`composer dumpautoload -o`).

Contao Version 4.4.26
Symfony Version 3.4.17

Edit: I see there were already some issues with this problem. But I haven't found a solution yet.

**Comment by hypergalaktisch** [comment]
I tryed to figure out the solution, but i couldn't reproduce the error after last update. I'll try again with given hints.

**Comment by OMOSde** [comment]
I had the same issue in a 4.4.32 installation. I found out that the directory name src/Eventlistener should be src/EventListener. After these change the problem with the autoloader is gone.

**Comment by hypergalaktisch** [comment]
Hopefully it's solved now with 2.0.4
